import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import {
  createOrUpdateFile,
  createBranch,
  openPullRequest,
  createGitHubRelease,
} from "../github.js";

const inputSchema = {
  owner: z.string().describe("GitHub repo owner"),
  repo: z.string().describe("GitHub repo name"),
  content: z.string().describe("The changelog markdown content"),
  action: z
    .enum(["file", "pull_request", "github_release"])
    .describe("Where to post the changelog: commit a file, open a PR, or create a GitHub Release"),
  version: z.string().optional().describe("Version string, used as the release tag name"),
  branch: z.string().optional().describe('Branch name for the PR. Defaults to "changelog/VERSION"'),
  file_path: z
    .string()
    .optional()
    .describe('Path in the repo for the changelog file. Defaults to "CHANGELOG.md"'),
  draft: z
    .boolean()
    .default(true)
    .describe("Whether a GitHub Release should be created as a draft"),
};

export function registerPostChangelog(server: McpServer): void {
  server.tool(
    "post_changelog",
    "Post a changelog to a GitHub repo as a file commit, pull request, or GitHub Release",
    inputSchema,
    async (args) => {
      try {
        const {
          owner,
          repo,
          content: rawContent,
          action,
          version,
          branch,
          file_path,
          draft,
        } = args;

        // Strip the AI rewrite instructions if they leaked into the content
        const instructionMarker = "---\n\n**Instructions for the AI assistant:**";
        const content = rawContent.includes(instructionMarker)
          ? rawContent.slice(0, rawContent.indexOf(instructionMarker)).trimEnd()
          : rawContent;

        const resolvedVersion = version ?? "unreleased";
        const resolvedPath = file_path ?? "CHANGELOG.md";

        switch (action) {
          case "file": {
            const commitMessage = `docs: update ${resolvedPath} for ${resolvedVersion}`;
            const url = await createOrUpdateFile(owner, repo, resolvedPath, content, commitMessage);
            return {
              content: [
                {
                  type: "text",
                  text: `Changelog committed to ${resolvedPath}.\n\n${url}`,
                },
              ],
            };
          }

          case "pull_request": {
            const branchName =
              branch ?? `changelog/${resolvedVersion.replace(/[^a-zA-Z0-9._-]/g, "-")}`;

            try {
              await createBranch(owner, repo, branchName);
            } catch (err) {
              const msg = err instanceof Error ? err.message : String(err);
              // Branch may already exist, that is acceptable
              if (!msg.includes("Reference already exists") && !msg.includes("422")) {
                throw err;
              }
            }

            const commitMessage = `docs: add changelog for ${resolvedVersion}`;
            await createOrUpdateFile(owner, repo, resolvedPath, content, commitMessage, branchName);

            const prUrl = await openPullRequest(
              owner,
              repo,
              `Release notes for ${resolvedVersion}`,
              `Automated changelog generated by Mergenote.\n\n---\n\n${content}`,
              branchName,
            );

            return {
              content: [
                {
                  type: "text",
                  text: `Pull request opened.\n\n${prUrl}`,
                },
              ],
            };
          }

          case "github_release": {
            const tagName = resolvedVersion.startsWith("v")
              ? resolvedVersion
              : `v${resolvedVersion}`;

            const isDraft = draft ?? true;

            const url = await createGitHubRelease(
              owner,
              repo,
              tagName,
              `Release ${resolvedVersion}`,
              content,
              isDraft,
            );

            return {
              content: [
                {
                  type: "text",
                  text: `GitHub Release created${isDraft ? " (draft)" : ""}.\n\n${url}`,
                },
              ],
            };
          }

          default:
            return {
              content: [
                {
                  type: "text",
                  text: `Unknown action: ${action}. Use "file", "pull_request", or "github_release".`,
                },
              ],
              isError: true,
            };
        }
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);

        if (message.includes("rate limit") || message.includes("403")) {
          return {
            content: [
              {
                type: "text",
                text: `GitHub API rate limit exceeded. Details: ${message}`,
              },
            ],
            isError: true,
          };
        }

        return {
          content: [{ type: "text", text: `Error posting changelog: ${message}` }],
          isError: true,
        };
      }
    },
  );
}
